-- Quel type de base de données  ?
--c 'est une base de donnée relationnelle
-- Quelle est l’importance des données à sauvegarder dans la base?
-- durant la phase de dev l'importance des données est surtout fonctionnelle donc une sauvegarde apres chaque changement important peut etre suffisant.
-- A partir de la mise en ligne parcontre il faudra mettre en place une vrai procedure de sauvegarde automatique car la moindre perte de donnée peut avoir de grave consequence
-- Quelle est la fréquence des modifications ?
-- a chaque nouvelle entrée serait l'ideal mais en prod cela peut engendrer des problemes car il y a des risque de blocage du site
--Quel est le meilleur moment pour effectuer les sauvegardes ?
--L'ideal serait donc de realiser les sauvergardes 2 a 3 fois par jour voir plus en fonction du trafic et lors de periodes dites creuses.
--quel type de sauvegarde?
--Le type de sauvegarde le plus adaptée semble etre:
--La sauvegarde différentielle,elle est conçue pour réduire la durée de restauration d’une base de données fréquemment modifiée. Seules les données modifiées depuis la dernière sauvegarde complète de la base de données et les lignes du journal des transactions nécessaires à la restauration sont sauvegardées. Attention :
-- une sauvegarde différentielle requiert une sauvegarde de base de données complète.
-- lors d’une succession de modifications sur une même ligne de données, seule la dernière est sauvegardée dans la sauvegarde différentielle;
--Pour cela il faut mettre en place un script ds cmd (voir cours cda)